I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/mini-game.rpy", line 2, in script
    init python:
  File "game/mini-game.rpy", line 2, in script
    init python:
  File "game/mini-game.rpy", line 17, in <module>
    while not(ind in inds):
NameError: name 'ind' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "G:\Program Files (x86)\renpy-8.1.2-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "G:\Program Files (x86)\renpy-8.1.2-sdk\renpy\main.py", line 564, in main
    renpy.game.context().run(node)
  File "game/mini-game.rpy", line 2, in script
    init python:
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "game/mini-game.rpy", line 2, in script
    init python:
  File "G:\Program Files (x86)\renpy-8.1.2-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "G:\Program Files (x86)\renpy-8.1.2-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/mini-game.rpy", line 17, in <module>
    while not(ind in inds):
NameError: name 'ind' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.2.23090503
ProjectOPD 1.0
Thu Nov  9 01:13:35 2023
